version: '3'

services:
  db:
    image: postgres:13.5
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: keycloak_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/datax
  kc:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: keycloak_db
      DB_USER: root
      DB_SCHEMA: public
      DB_PASSWORD: root
      KEYCLOAK_HOSTNAME: backend-keycloak-auth
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
